name: Rolling Semi-Binary Build
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  semi_binary_rolling:
    name: semi binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: testing}
    env:
      UPSTREAM_WORKSPACE: faze4_ros.repos
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
